### ISSUE TITLE
Workflow trigger?

### ISSUE THREAD

**Issue by ProximaHaiz** [sensorocean/support#1]
Could you please explain what initiates the workflow? What is the trigger to run the steps?

**Comment by sensorocean** [comment]
Hello ProximaHaiz,

Thank you for asking. 

The workflow of the network runs every time the Controller receives data from a sensor of that network. In other words, the trigger is the event of receiving a record with the data from a sensor.

For example, if you have two sensors in the network that send records every 10 minutes, the workflow will run 12 times an hour.

Of course, you can differentiate the sensors and define the steps to run by setting the conditions and the flow of the processes.

Check our [Wiki](https://github.com/sensorocean/support/wiki) pages for more information. Please, let me know if more explanation is needed.

-SensorOcean Team
