### ISSUE TITLE
Integration with IFTTT

### ISSUE THREAD

**Issue by olegedly** [sensorocean/support#2]
Hello,

I want to send an SMS when my sensor goes beyond a threshold. I can do it with IFTTT. Do you have integration with IFTTT? How to do it?

Thank you

**Comment by ruslanolkhovsky** [comment]
Hello,

Thank you for asking. Yes, the platform supports integration with IFTTT as well as with any other system that provides REST API. It is implemented in the [**use_call_webhook**](https://github.com/sensorocean/support/wiki/Workflow:-Methods#method-use_call_webhook) workflow method.

So, to trigger an event in your IFTTT applet simply call a **use_call_webhook** method in the workflow when the sensor's value exceeds the threshold. The parameters of the method will look like this:

```
{ 
  "url": "https://maker.ifttt.com/trigger/{event}/with/key/{key}", 
  "method": "POST", 
  "headers": {}, 
  "data": { "value1" : "", "value2" : "", "value3" : "" }, 
  "response_key": "your_name_of_the_response_key" 
}
```

where the _{event}_ and the _{key}_ are your settings from the IFTTT. The method could be _"GET"_. And the _"data"_ is optional. Most probably, you can use it for the text of the SMS message.

I hope it helps. Please, let me know if more explanation needed.

-SensorOcean Team

**Comment by sensorocean** [comment]
Hello,

Thank you for asking. Yes, the platform supports integration with IFTTT as well as with any other system that provides REST API. It is implemented in the [**use_call_webhook**](https://github.com/sensorocean/support/wiki/Workflow:-Methods#method-use_call_webhook) workflow method.

So, to trigger an event in your IFTTT applet simply call a **use_call_webhook** method in the workflow when the sensor's value exceeds the threshold. The parameters of the method will look like this:

```
{ 
  "url": "https://maker.ifttt.com/trigger/{event}/with/key/{key}", 
  "method": "POST", 
  "headers": {}, 
  "data": { "value1" : "", "value2" : "", "value3" : "" }, 
  "response_key": "your_name_of_the_response_key" 
}
```

where the _{event}_ and the _{key}_ are your settings from the IFTTT. The method could be _"GET"_. And the _"data"_ is optional. Most probably, you can use it for the text of the SMS message.

I hope it helps. Please, let me know if any questions or more explanation needed.

-SensorOcean Team
