### ISSUE TITLE
Add filter/search to the Controller log

### ISSUE THREAD

**Issue by aemanukyan** [sensorocean/support#3]
Hey, our team has tested your platform. Everything looks good but there are some features we would like to see in future releases.

It would be nice to have a filter (Info/Error/Warning and so on) and a simple search in the log on the Controller tab of the network's settings. Also, an email notification in case of an error in the log could be useful.

**Comment by ruslanolkhovsky** [comment]
Hey David,

Thank you for the ideas. We will review and let you know if and when those to be implemented.

-SensorOcean Team

**Comment by sensorocean** [comment]
Hey David,

Thank you for the ideas. We will review and let you know if and when those to be implemented.

-SensorOcean Team

**Comment by sensorocean** [comment]
Planned for next releases.
