### ISSUE TITLE
Hello! I can't register on your platform, an activation code is required during registration, how do I get it?[BUG]

### ISSUE THREAD

**Issue by Roman-Buratino** [sensorocean/support#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and code samples**
If applicable, add screenshots or code samples to help explain your problem.

**Software environment and additional context**
Describe your software environment and add any other context about the problem here.

**Comment by sensorocean** [comment]
Thank you for the question. 

We constantly develop and improve the platform. Therefore, at the moment, we grant access to the platform by request only. Please, send us a message to support@sensorocean.com, say a few words about the project, and we will get back to you with a redeem code that you can use in the registration process.
